### PR TITLE
Fix message fetch loop from crashing if messages is empty

### LINKED ISSUE #75: Bot crashes if theres an empty channel
the fetchMessages() loop assumes there will be a last() message.

### PR DESCRIPTION
**Pull request by mooper60**
Closes #75

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -213,13 +213,17 @@ async function fetchAllMessages(textChannel) {
     let options = { limit: 100, before: null };
     let messagesSize;
 
+    if(textChannel.name == "rocket-league") debugger;
```
Comment (mooper60) [inline index.js]: Remove debugger line
